### ISSUE TITLE
client_max_body_size

### ISSUE THREAD

**Issue by samuelbirch** [nystudio107/nginx-craft#10]
it would be good to include client_max_body_size to match craft's default of 16M

**Comment by khalwat** [comment]
There's a note for it in the docs, but you're right, I should include it in the config as well.

**Comment by khalwat** [comment]
Done in 1.0.13:

https://github.com/nystudio107/nginx-craft/releases/tag/1.0.13

I actually ended up doing:

```
    # Disable limits on the maximum allowed size of the client request body
    client_max_body_size 0;

```

...so we can just let Craft decide what the limits should be.

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
