### ISSUE TITLE
duplicate "client_max_body_size" in somedomain.com.conf

### ISSUE THREAD

**Issue by uzerus** [nystudio107/nginx-craft#14]
` "client_max_body_size" directive is duplicate in /etc/nginx/sites-available/somedomain.com.conf:174`

```
# Disable limits on the maximum allowed size of the client request body
 :50  | client_max_body_size 0;
```

```
# Misc settings
sendfile off;
:174  | client_max_body_size 100m;
}
```

so it should be 0 or 100m; ?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/nginx-craft/commit/e16537803aef1dbe361d7867d191df589d684169
