### ISSUE TITLE
Forge example with Fastcgi

### ISSUE THREAD

**Issue by johneemac** [nystudio107/nginx-craft#16]
Hi, any chance of an example with the Fast cgi caching setup with Forge?

I've combined the older Forge example on NyStudio with the newer forge example found in this repo. It all works fine on the front end with caching working. The problem i'm having however is that i cannot login to the admin. The login page just refreshes. I can log in with a simpler config set up though.

Any pointers appreciated. Thanks.

**Comment by khalwat** [comment]
A good place to see that would be here: https://nystudio107.com/blog/static-caching-with-craft-cms

(the full config is at the bottom of the article)

**Comment by johneemac** [comment]
If anyone else has the problem. Path info was the problem. Setting usePathInfo to true in config/general was the magic that got it working.
