### ISSUE TITLE
Mitigate httpoxy vulnerability

### ISSUE THREAD

**Issue by 3noch** [nystudio107/nginx-craft#2]
According to https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/ and https://httpoxy.org/, you should add this configuration to your ngnix config:

```
fastcgi_param HTTP_PROXY "";
```

**Comment by khalwat** [comment]
It looks like it's already there in the default `fastcgi_params ` (which we include):

```
forge@nys-production /etc/nginx $ cat fastcgi_params | grep PROXY
fastcgi_param   HTTP_PROXY  "";

```

**Comment by 3noch** [comment]
Ah but only for Forge. If anyone uses this on another provider they may not be so lucky. It'd be worth mentioning at least.

**Comment by 3noch** [comment]
In fact, Forge is specifically designed for PHP so that makes sense. I know that Ubuntu does not include it.

**Comment by khalwat** [comment]
Good point! Added it -> https://github.com/nystudio107/nginx-craft
