### ISSUE TITLE
TLSv1.3

### ISSUE THREAD

**Issue by 3noch** [nystudio107/nginx-craft#3]
Have you tried allowing TLSv1.3 with your configuration?

**Comment by khalwat** [comment]
Do any stable browsers come with it enabled by default yet?

**Comment by khalwat** [comment]
https://forum.nginx.org/read.php?2,264595,264597#msg-264597

```
Support for SSL and TLS in nginx relies on OpenSSL, so TLS 1.3 
will be supported by nginx once added to OpenSSL.

```

https://github.com/openssl/openssl/issues/963
