### ISSUE TITLE
Question: Why is SSI include active?

### ISSUE THREAD

**Issue by hiasl** [nystudio107/nginx-craft#34]
### Question
Your production conf file has server side include activated. Is there a specific reason for this, because I guess this also creates some overhead not needed for a Craft project?

**Comment by khalwat** [comment]
I use it on all of my Craft projects -- the overhead is likely minimal, but you can turn it off if you like. https://github.com/nystudio107/craft/blob/craft-webpack/cms/templates/_boilerplate/_partials/critical-css.twig#L4
