### ISSUE TITLE
Problems with localised Craft installation

### ISSUE THREAD

**Issue by thomas-xo** [nystudio107/nginx-craft#5]
We have a setup like this for our site:

dev.domain.com/de-de/   <- default
dev.domain.com/gb-en/

and try to use your Forge example configuration. The frontend seems working without problems, but the backend (Craft CMS Control panel) is only accessible via

dev.domain.com/de-de/admin
dev.domain.com/gb-en/admin

thus producing errors with loading the needed css/js for the control panel.

On an apache webserver with the same site, the Craft CMS control panel is accessible via:

dev.domain.com/admin

and running without any problems.

Any idea what's going wrong?

**Comment by alexagui** [comment]
I noticed similar issue on my localized site as well. The front-end loaded fine but the admin (control panel) CSS+JS was all out whack.  

I haven't had chance to troubleshoot yet but my idea is to include  the conf files individually to see which is the culprit. I suspect it's `cache-busting.conf`.

**Comment by khalwat** [comment]
@alexagui If the AdminCP can't load the CSS/JS, then then perhaps you've changed the cpTrigger? There is a rule in the Nginx configs to handle sending CSS/JS requests through to the AdminCP

**Comment by alexagui** [comment]
Thanks @khalwat  That was my issue.
